language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

os:
  - linux
  - osx

install: true # yarn bug

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yarn; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=/usr/bin/google-chrome; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libappindicator1 fonts-liberation; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i google-chrome*.deb; fi

before_script:
  - npm i -g npm@^5.3.0 && npm --version
  - npm install webdriver-manager
  - npm run webdriver-manager update
  - npm install
  - npm run webdriver-update
  - npm rebuild node-sass
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - nohup bash -c "webdriver-manager start &" # Protractor CI

after_failure:
  - cat $TRAVIS_BUILD_DIR/npm-debug.log

branches:
  only:
    - master
    - travis

cache:
  directories: node_modules

script:
  - npm run tests.all
